version: "2"

run:
  timeout: 5m
  go: '1.24'  # Use current Go version

linters:
  default: fast  # Use the default fast linters
  enable:
    # Additional linters beyond defaults
    - misspell
    - goconst
  disable:
    # Temporarily disabled linters (TODO: re-enable and fix issues)
    # These linters found 172+ issues that need to be addressed
    - gosec       # Security issues (13 issues) - temporarily disabled
    - godot       # Comments should end with periods (many issues) - partially fixed
    - nlreturn    # Newlines before returns/breaks/continues (many issues) - partially fixed
    - cyclop      # Cyclomatic complexity (5 issues)
    - depguard    # Import restrictions (35 issues)
    - funcorder   # Function ordering (4 issues)
    - funlen      # Function length (2 issues)
    - gochecknoinits # No init functions (3 issues)
    - gocognit    # Cognitive complexity (1 issue)
    - godox       # TODO comments (2 issues)
    - gocyclo     # Cyclomatic complexity (overlaps with cyclop)
    - lll         # Line length (1 issue)
    - mnd         # Magic numbers (13 issues)
    - nestif      # Nested if (1 issue)
    - prealloc    # Slice preallocation (2 issues)
    - tagalign    # Struct tag alignment (50 issues)
    - testpackage # Test package naming (2 issues)
    - unparam     # Unused parameters (1 issue)
    - wsl         # Whitespace (25 issues)
  exclusions:
    paths:
      - third_party$
      - vendor$
    rules:
      # Exclude some linters from running on tests
      - path: '_test\.go'
        linters:
          - gocyclo
          - errcheck
          - gosec
          - lll
          - goconst
      
      # Exclude some linters from running on CLI commands
      - path: 'cmd/'
        linters:
          - lll  # CLI help text can be long
          - goconst

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  goconst:
    min-len: 2
    min-occurrences: 3
  
  gocyclo:
    min-complexity: 15
  
  goimports:
    local-prefixes: pkm-sync
  
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment  # Can be noisy
  
  lll:
    line-length: 120
  
  misspell:
    locale: US
  
  unparam:
    check-exported: false

severity:
  default: error