# ko configuration for pkm-sync
defaultPlatforms:
  - linux/amd64
  - linux/arm64
  - darwin/amd64
  - darwin/arm64

# Use distroless base image for security
defaultBaseImage: gcr.io/distroless/static:nonroot

# Environment variables for the container
env:
  - CGO_ENABLED=0

# Build flags
flags:
  - -trimpath
  - -ldflags
  - "-s -w -X main.Version={{.Env.VERSION}} -X main.Commit={{.Env.COMMIT}} -X main.Date={{.Env.DATE}}"